[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/morikuni/aec"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/inlets/inlets-operator"
  version = "0.4.2"
